name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install CI dependencies
      run: |
        python -m pip install --upgrade pip	
        pip install pipenv
        pipenv install --dev
    - name: Run Integration Tests
      run: |
        pipenv run integration-test
